mod 'boxen',     '2.3.3', :github_tarball => 'boxen/puppet-boxen'
mod 'homebrew',  '1.2.0',  :github_tarball => 'boxen/puppet-homebrew'
mod 'gcc',       '0.0.2',       :github_tarball => 'boxen/puppet-gcc'